"""Modify model for external API

Revision ID: 3806b46f7f00
Revises: 4fafafd2400f
Create Date: 2019-11-03 23:26:02.357848

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3806b46f7f00'
down_revision = '4fafafd2400f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campus', sa.Column('external_id', sa.Integer(), nullable=True))
    op.alter_column('campus', 'page_url',
                    existing_type=sa.TEXT(),
                    server_default=None,
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campus', 'page_url',
                    existing_type=sa.TEXT(),
                    server_default='',
                    nullable=False)
    op.drop_column('campus', 'external_id')
    # ### end Alembic commands ###
