"""Add columns for feature participation

Revision ID: 55696107a6b9
Revises: 79e0c9de90f0
Create Date: 2019-10-14 13:17:49.813805

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55696107a6b9'
down_revision = '79e0c9de90f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('string_id', sa.String(length=256), nullable=False, unique=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('globally_available', sa.Boolean(), default=False, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('feature_participation',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('feature_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'feature_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_participation')
    op.drop_table('feature')
    # ### end Alembic commands ###
