"""Drop onboarding_done as this will not be necessary anymore, and add an enabled field.

Revision ID: 5cd86de4dffe
Revises: 93b9de63cd7b
Create Date: 2020-02-25 10:59:52.562751

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5cd86de4dffe'
down_revision = '93b9de63cd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('enabled', sa.Boolean(), nullable=False, default=True,
                                        server_default=sa.sql.expression.true()))
    op.drop_column('app_user', 'onboarding_done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('onboarding_done', sa.BOOLEAN(), autoincrement=False, nullable=False,
                                        default=False, server_default=sa.sql.expression.false()))
    op.drop_column('app_user', 'enabled')
    # ### end Alembic commands ###
