"""Add a table to indicate restaurant closures

Revision ID: 7751a57b029e
Revises: 55696107a6b9
Create Date: 2019-10-28 00:19:18.033714

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7751a57b029e'
down_revision = '55696107a6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closing_days',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('campus_id', sa.Integer(), nullable=False),
                    sa.Column('first_day', sa.Date(), nullable=False),
                    sa.Column('last_day', sa.Date(), nullable=False),
                    sa.Column('translatable_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
                    sa.ForeignKeyConstraint(['translatable_id'], ['translatable.id'], onupdate='CASCADE',
                                            ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('closing_days')
    # ### end Alembic commands ###
