"""Initial imported database structure

Revision ID: a223b578f7b0
Revises: 
Create Date: 2019-10-13 22:02:33.540908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a223b578f7b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Translatable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_language', sa.String(length=5), nullable=False),
    sa.Column('original_text', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('menu_day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['Campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facebook_id', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('campus_mon_id', sa.Integer(), nullable=False),
    sa.Column('campus_tue_id', sa.Integer(), nullable=False),
    sa.Column('campus_wed_id', sa.Integer(), nullable=False),
    sa.Column('campus_thu_id', sa.Integer(), nullable=False),
    sa.Column('campus_fri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campus_fri_id'], ['Campus.id'], ),
    sa.ForeignKeyConstraint(['campus_mon_id'], ['Campus.id'], ),
    sa.ForeignKeyConstraint(['campus_thu_id'], ['Campus.id'], ),
    sa.ForeignKeyConstraint(['campus_tue_id'], ['Campus.id'], ),
    sa.ForeignKeyConstraint(['campus_wed_id'], ['Campus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id')
    )
    op.create_table('Translation',
    sa.Column('translatable_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('translation', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['translatable_id'], ['Translatable.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('translatable_id', 'language')
    )
    op.create_table('MenuItem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('translatable_id', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.Enum('SOUP', 'MEAT', 'VEGAN', 'GRILL', 'PASTA_MEAT', 'PASTA_VEGAN', name='foodtype'), nullable=False),
    sa.Column('price_students', sa.String(length=8), nullable=False),
    sa.Column('price_staff', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['Menu.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translatable_id'], ['Translatable.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MenuItem')
    op.drop_table('Translation')
    op.drop_table('Subscription')
    op.drop_table('Menu')
    op.drop_table('Translatable')
    op.drop_table('Campus')
    # ### end Alembic commands ###
